name: Test and Deploy

on: pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.8

      - name: Cache bundle
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: bundle-v1-${{ hashFiles('Gemfile.lock') }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.22.12' # Node.jsのバージョンを指定

      - name: Install Bundler dependencies
        run: |
          bundle config --local path vendor/bundle
          bundle config --local without production
          bundle install

      - name: Install JavaScript dependencies
        run: yarn install

      - name: Precompile assets
        run: RAILS_ENV=test bundle exec rails assets:precompile

      - name: Run tests
        run: bundle exec rails test
