name: Test and Deploy

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.8

      - name: Cache bundle
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: bundle-v1-${{ hashFiles('Gemfile.lock') }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.22.12' # Node.jsのバージョンを指定

      - name: Install Bundler dependencies
        run: |
          bundle config --local path vendor/bundle
          bundle config --local without production
          bundle install

      - name: Cache yarn
        uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-v1-${{ hashFiles('yarn.lock') }}

      - name: Install JavaScript dependencies
        run: yarn install

      - name: Precompile assets
        run: RAILS_ENV=test bundle exec rails assets:precompile

      - name: Run tests
        run: bundle exec rails test

  deploy:
    name: Deploy app to AWS
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.22.12'
  
      - name: Install SSH key
        run: |
          mkdir -p -m 700 ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/rails-deploy-webapp
          chmod 600 ~/.ssh/rails-deploy-webapp
  
      - name: Deploy
        run: |
          eval $(ssh-agent)
          ssh-add ~/.ssh/rails-deploy-webapp
          ssh -o StrictHostKeyChecking=no -A webapp@${{ secrets.TARGET_HOSTNAME }} "
          cd rails-deploy &&
          git pull origin main &&
          nvm use 12 &&
          yarn install &&
          ~/.rbenv/shims/bundle config --local deployment true &&
          ~/.rbenv/shims/bundle config --local without development:test &&
          ~/.rbenv/shims/bundle install &&
          mkdir -p tmp/pids &&
          touch tmp/pids/server.pid &&
          RAILS_ENV=production ~/.rbenv/shims/bundle exec rails assets:precompile &&
          RAILS_ENV=production ~/.rbenv/shims/bundle exec rails db:migrate &&
          ~/.rbenv/shims/bundle exec pumactl restart"
